name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Compile code
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
          mkdir build
          cmake -B build -S .
          cmake --build build
          
      - name: Run application
        run: ./build/tests

