name: basic
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compile code
        run: g++ main.cpp my_add.cpp -o main
      - name: Run application
        run: ./main 4 6
